# Generated by Django 5.0.2 on 2024-02-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_urlfield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='urlfield',
            new_name='url_info',
        ),
    ]
