# Generated by Django 5.0.2 on 2024-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_urlfield_project_url_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_info',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección Web'),
        ),
    ]
